namespace: demo-ns

resourcesReplicaCount: 2
songsReplicaCount: 2
resourcesDbReplicaCount: 1
songsDbReplicaCount: 1

resourcesImage: "microservices-intro/resources-ms:2.0.0"
songsImage: "microservices-intro/songs-ms:2.0.0"
resourcesDbImage: "postgres:17"
songsDbImage: "postgres:17"

storageClass: standard
storageSize: 1Gi

# Database credentials (can be overridden during install)
dbUser: postgres
dbPassword: postgres
springDatasourcePassword: postgres

# Host path for songs PV
hostPathSongs: /mnt/data/songs
