apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: resources-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resources-ms-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-ms-pod
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-ms
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: resources-ms-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: resources-ms-pod
        owner: ievgengusar
    spec:
      containers:
        - name: resources-ms-container
          image: microservices-intro/resources-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_MS_NAME
              value: "resources-ms"
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: RESOURCES_DB_URL
              value: "resources-db"
            - name: RESOURCES_DB_PORT
              value: "5433"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password123"
            - name: SONGS_MS_URL
              value: "songs-ms"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: ENABLE_EUREKA_CLIENT
              value: "false"
            - name: EUREKA_URI
              value: "eureka"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: songs-ms-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: songs-ms-pod
        owner: ievgengusar
    spec:
      containers:
        - name: songs-ms-container
          image: microservices-intro/songs-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_MS_NAME
              value: "songs-ms"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: SONGS_DB_URL
              value: "songs-db"
            - name: SONGS_DB_PORT
              value: "5432"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password123"
            - name: ENABLE_EUREKA_CLIENT
              value: "false"
            - name: EUREKA_URI
              value: "eureka"
          volumeMounts:
            - name: songs-storage
              mountPath: /data
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
