apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resources-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /resources$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: resources
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: resources-ms
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: songs-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /songs/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: songs
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: songs-ms
                port:
                  number: 8081
