apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.dbUser }}"
  POSTGRES_PASSWORD: "{{ .Values.dbPassword }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.springDatasourcePassword }}"
