apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  namespace: "{{ .Release.Namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.storageSize }}"
